### ISSUE TITLE
Slashes and backslashes in client root.

### ISSUE THREAD

**Issue by tomalec** [ericmartel/Sublime-Text-2-Perforce-Plugin#1]
Hi, I've had a problem with saving files with your plugin, because my `p4 info` returns:

```
Client root: c:/path
Current directory: c:\path\to\branch
```

I made a quick workaround with 6207c3816b92b9d2219b92b22d500cfb3bddcb8c but hopefully something nicer could be done.

**Comment by ericmartel** [comment]
Thanks for this input, I'll see if I can repro locally and submit a fix.
I'll take a look at your workaround.

Cheers

On 2012-01-10 11:25 AM, "Tomek Wytrębowicz" <
reply@reply.github.com>
wrote:

Hi, I've had a problem with saving files with your plugin, because my `p4
info` returns:

```
Client root: c:/path
Current directory: c:\path\to\branch
```

I made a quick workaround with 6207c3816b92b9d2219b92b22d500cfb3bddcb8c but
hopefully something nicer could be done.

---

Reply to this email directly or view it on GitHub:
https://github.com/ericmartel/Sublime-Text-2-Perforce-Plugin/issues/1

**Comment by ericmartel** [comment]
Changed the folder check to all forward slashes in submit 05119408a8243b2e4c0825d6cadf08b01dc4f326

**Comment by ericmartel** [comment]
I improved to code to work with os.sep, please let me know if it fixes your issue
