### ISSUE TITLE
Sublime Text 3

### ISSUE THREAD

**Issue by nitaigao** [ericmartel/Sublime-Text-2-Perforce-Plugin#15]
Please can you implement support for Sublime Text 3.

**Comment by ericmartel** [comment]
Thanks Nicholas! I wasn't aware that the beta was released... I'll take a look at it, ever since I initially wrote the plugin I wanted to rewrite it in a more robust manner... I guess now is a good time!

**Comment by maheshjag** [comment]
@ericmartel However, if you want a patch to get it working on ST3 in the meanwhile, I'm happy to send you a pull request with the fixes I've done to get it to work under ST3

**Comment by amcdnl** [comment]
+1 for ST3 Support

**Comment by trentrolf** [comment]
Also interested in ST3 support.  Patches made by @maheshjag seem to work for me.

**Comment by ericmartel** [comment]
I'm glad the suggested changes work, however as you can see in the name of the repository, this is for ST2 only, if I was to make the changes it would break the plugin for the people who didn't switch to ST3.

I am currently in the process of rewriting the plugin, fixing design issues that I had in the first version because it was never planned to grow so big.

**Comment by maheshjag** [comment]
I understand, Eric. Will wait for your new release!

## 

Mahesh Jagadeesan
